### ISSUE TITLE
How import .dat backup from an older wallet to a new one

### ISSUE THREAD

**Issue by paco76** [bitcoinbabys/Stronghands-New#2]
I have a windows wallet version 0.153 and I just download win version 0.7301
the list of nodes I have won't connect so I made a backup file of the wallet (backup.dat file)
my question is how is it possible to import that file to the new wallet, on the new wallet I didn't find import option?

thank you!

**Comment by paco76** [comment]
somebody ??

**Comment by bumbacoin** [comment]
it should be a matter of **_copying_** your existing wallet.dat into the new stronghands datadirectory, SHND
please join the discord server for more help,
you can find the link here
https://www.stronghands.info/
